<?php

namespace App\Services;

use App\Models\Project;
use Illuminate\Support\Facades\Storage;
use ZipArchive;

class CodeGeneratorService
{
    public function generateProjectFiles(Project $project)
    {
        $code = $project->generated_code;
        $fileStructure = $project->file_structure;

        $zipPath = $this->createZipFromStructure($code, $fileStructure, $project->name);
        
        $project->update([
            'build_logs' => array_merge($project->build_logs ?? [], ['Zip package created successfully'])
        ]);

        return $zipPath;
    }

    protected function createZipFromStructure($code, $fileStructure, $projectName)
    {
        $zip = new ZipArchive();
        $zipFileName = storage_path("app/projects/{$projectName}.zip");
        
        if ($zip->open($zipFileName, ZipArchive::CREATE) === TRUE) {
            $this->addFilesToZip($zip, $code, $fileStructure);
            $zip->close();
            return $zipFileName;
        }
        
        throw new \Exception('Could not create ZIP file');
    }

    protected function addFilesToZip($zip, $code, $structure, $path = '')
    {
        foreach ($structure as $key => $value) {
            $currentPath = $path ? $path . '/' . $key : $key;
            
            if (is_array($value)) {
                // It's a directory
                $zip->addEmptyDir($currentPath);
                $this->addFilesToZip($zip, $code, $value, $currentPath);
            } else {
                // It's a file - check if we have code for it
                $fileContent = $code[$value] ?? "// File: $value\n// Generated by ALICE Pro";
                $zip->addFromString($currentPath, $fileContent);
            }
        }
    }

    public function generateReadme($project)
    {
        return "
# {$project->name}

Generated by ALICE Pro - AI-Powered Development Platform

## Project Details
- **Type**: {$project->type}
- **Generated**: {$project->created_at}
- **AI Models**: " . implode(', ', $project->ai_models_used) . "

## Getting Started

" . ($project->instructions ?? 'Follow the instructions specific to your project type') . "

## Deployment

This project can be deployed to:
- GitHub Pages
- Render.com
- Netlify
- Vercel

---
*Powered by ALICE Pro - Making development accessible to everyone*
        ";
    }
}